server:
  port: 8082
  error:
    include-message: always


spring:
  application:
    name: kanban-board-service

  data:
    mongodb:
      uri: mongodb://mongodb-container:27017/kanban-board

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
