
server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: kanban-board-service

  datasource:
    url: jdbc:mysql://kanban-database-container:3306/kanban_database?createDatabaseIfNotExist=true
    username: root
    password: Saraneswar4896
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
