version: "3"
services:
  eureka-server-service:
    build: eureka-server/
    container_name: eureka-server-service-container
    networks: [ gaming-application-network ]
    ports:
      - "8761:8761"

  mysql-database-service:
    image: mysql
    container_name: mysql-database-container
    ports:
      - "3307:3306"
    networks: [ kanban-board-application-network ]
    environment:
      MYSQL_ROOT_PASSWORD: Saraneswar4896
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  user-auth-service:
    build: user-auth/
    container_name: user-auth-service-container
    ports:
      - "8081:8081"
    networks: [ kanban-board-application-network ]
    depends_on: [ mysql-database-service,eureka-server-service ]
    restart: always

  mongodb-database-service:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27018:27017"
    networks: [ kanban-board-application-network ]

  kanban-board-service:
    build: kanban-board/
    container_name: kanban-board-container
    ports:
      - "8082:8082"
    networks: [ kanban-board-application-network ]
    depends_on: [ mongodb-database-service ,eureka-server-service]
    restart: always

  api-gateway-service:
    build: api-gateway/
    container_name: api-gateway-service-container
    ports:
      - "9000:9000"
    networks: [ kanban-board-application-network ]
    depends_on: [ eureka-server-service ]

networks:
  kanban-board-application-network:
    driver: bridge




