version: "3"
services:
  mysql-database-service:
    image: mysql
    container_name: mysql-database-container
    ports:
      - "3307:3306"
    networks: [ kanban-board-application-network ]
    environment:
      MYSQL_ROOT_PASSWORD: Saraneswar4896
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  user-auth-service:
    build: user-auth/
    container_name: user-auth-service-container
    ports:
      - "8081:8081"
    networks: [ kanban-board-application-network ]
    depends_on: [ mysql-database-service]
    restart: always

  mongodb-database-service:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27018:27017"
    networks: [ kanban-board-application-network ]

  gaming-service:
    build: gaming-service/
    container_name: gaming-service-container
    ports:
      - "8083:8083"
    networks: [ gaming-application-network ]
    depends_on: [ mongodb-database-service ,eureka-server-service ]
    restart: always

networks:
  kanban-board-application-network:
    driver: bridge




