server:
  port: 8081

  error:
    include-message: always

spring:
  application:
    name: user-auth-service


  datasource:
    url: jdbc:mysql://mysql-database-container:3306/users?createDatabaseIfNotExist=true
    username: root
    password: Saraneswar4896
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
